# Generated by Django 3.2.6 on 2021-08-27 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Enterprise',
        ),
    ]
